services:
  backend:
    image: dinnusaideep/capstone-backend:latest
    container_name: capstone-backend-prod
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - db
    restart: always

  frontend:
    image: dinnusaideep/capstone-frontend:latest
    container_name: capstone-frontend-prod
    ports:
      - "80:80"
    restart: always

  db:
    image: postgres:15
    container_name: capstone-db-prod
    environment:
      POSTGRES_DB: capstone
      POSTGRES_USER: capstone
      POSTGRES_PASSWORD: capstone
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_prod:
